name: Python package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run make
      run: pip install -r requirements.txt

    - name: Test with pytest
      run: pytest
